### ISSUE TITLE
Should output String()

### ISSUE THREAD

**Issue by bep** [y0ssar1an/q#3]
I see this:

```
Render p.NodeType=hugolib.NodeType(3)
```

`NodeType` is an `int`, but implements the `Stringer` interface, so I would expect the `String()` output to be in there somewhere.

**Comment by y0ssar1an** [comment]
I'm relying on [`kr/pretty`](https://github.com/kr/pretty) for all the pretty printing. There is exactly one call to `pretty.Print()` in `q`. This is a legit issue, it should be raised on `kr/pretty`, not here. In any case, thank you very much for making me aware of the problem!

**Comment by bep** [comment]
@y0ssar1an I maintain enough open source to sympathize with your need to delegate work, but that also means that I have too much work to do to actually do something about this -- I'll just stop use `Q` and stop telling my friends about it.

Having  `iota` filled enum type constants with 100 different values, and then have to guess what 64 means in the Q log ... (I know I can call `String()` explicit, but your makes a big point about the simple).
