### ISSUE TITLE
use broken with go mod

### ISSUE THREAD

**Issue by reedobrien** [y0ssar1an/q#55]
When tryinq to use `q` in a project which uses go mod, any command run exits with an error. I am a little suspicious that the issue is really just a bad error message, but I don't quite see how it is getting triggered. Hopefully it make sense to you.

Here is a very simple example that shows the issue. 

Create a dir with the following contents in main.go:
```
// Package main provides an example of q/mod failure
package main

import "github.com/y0ssar1an/q"

func main() {
	i := 1
	t := []int{1, 2, 3}
	q.Q(i, t)
}
```

run `go mod init github.com/reedobrien/w`

run `go build` and get the error:
```
go: finding github.com/golangci/tools v0.0.0-20180902102414-2cefd77fef9b
go: github.com/golangci/tools@v0.0.0-20180902102414-2cefd77fef9b: unknown revision 2cefd77fef9b
```

I don't see golangci or tools in the q repo... so I suspect someone doing something clever vending dependencies, a bug in go mod, or both. Also I've been away from go for a bit and haven't used modules in anger before my current project. So I am a bit lost with them. Hopefully this rings a bell in your head.

**Comment by y0ssar1an** [comment]
Sorry for the trouble, @reedobrien. The dependency on `golangci-lint` was removed on `master` branch, but it was still present in the latest tagged release ([v1.0.6](https://github.com/y0ssar1an/q/releases/tag/v1.0.6)). I just cut [v1.0.7](https://github.com/y0ssar1an/q/releases/tag/v1.0.7), which should resolve the issue after you run this command:

```sh
GO111MODULE=on go get github.com/y0ssar1an/q@v1.0.7
```

Thanks for taking the time to report the issue! Please reopen if the issue persists.

**Comment by reedobrien** [comment]
WFM now. Thanks.
