### ISSUE TITLE
What should do when i use this on production environment?

### ISSUE THREAD

**Issue by iineva** [y0ssar1an/q#58]
Should i delete `q` on production environment?

**Comment by y0ssar1an** [comment]
It's not intended for use in production, but it's unlikely to cause harm. The worst thing I can think of that might happen is that the `/tmp/q` file grows to gigabytes in size. That might cause problems.

If you want to log pretty-printed Go objects in prod, you can use [`kr/pretty`](https://godoc.org/github.com/kr/pretty) with a production logger like [`logrus`](https://godoc.org/github.com/sirupsen/logrus) or [`go-kit/kit/log`](https://godoc.org/github.com/go-kit/kit/log).
```go
import (
    "github.com/go-kit/kit/log"
    "github.com/kr/pretty"
)
...
logger.Log("myobject", pretty.Sprintln(myobject))
```

**Comment by iineva** [comment]
@y0ssar1an thanks.
